# Project Name
TARGET = FlasherClient

# Sources
CPP_SOURCES = FlasherClient.cpp

# Library Locations
# Adjust these to match your Daisy toolchain installation
# Default assumes libDaisy and DaisySP are siblings to this project
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
